822 upgrade dependencies
IsaiahDahlberg/dwolla-v2-csharp pull request #1
Opened 2023-01-03 20:37 UTC by IsaiahDahlberg

Replaced Newtonsoft.Json with System.Text.Json
Setup static HttpClient in DwollaClient

2023-01-03 21:50 UTC, natehitze commented
![image](https://user-images.githubusercontent.com/3506334/210446542-0b7dda61-64cf-4349-b686-bec7f3534068.png)
Build warnings on the client can be addressed here also. I don't think the hiding was intentional so these `Links` properties can just be removed

Some tests are failing
![image](https://user-images.githubusercontent.com/3506334/210447216-32887b80-c6f3-4794-82a6-e6e518aa99c2.png)

2023-01-03 22:23 UTC, natehitze requested changes

2023-01-03 22:23 UTC, natehitze commented on Dwolla.Client/Models/Requests/JsonProperyNameAttribute.cs
> +	internal class JsonProperyNameAttribute : Attribute
Looks like this file can be deleted

2023-01-03 22:23 UTC, natehitze commented on Dwolla.Client/DateOnlyConverter.cs
> + 	public class DateOnlyConverter : JsonConverter<DateTime>
Add unit test coverage for this converter please, I don't see anything existing that covers it

2023-01-03 22:23 UTC, natehitze commented on Dwolla.Client/Rest/RestClient.cs
>      public class RestClient : IRestClient
Revert this back to what they had initially with `DwollaClient` managing the `HttpClient`. I'll explain more tomorrow

2023-01-04 19:12 UTC, natehitze requested changes

2023-01-04 19:12 UTC, natehitze commented on Dwolla.Client/Dwolla.Client.csproj
> +    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
This AspNet reference shouldn't be required

2023-01-04 19:12 UTC, natehitze commented on Dwolla.Client/DwollaClient.cs
> +            new DwollaClient(new RestClient(CreateHttpClient()), isSandbox);
This is still effectively a singleton `HttpClient`. You need to either:

1. Keep a singleton `RestClient`, remove `HttpClient` from its constructor, add `HttpClient` parameter to its `Send` method
2. Remove singleton `RestClient`, inside `DwollaClient`'s `Send` method new up a `RestClient` with an `HttpClient` obtained from `CreateHttpClient`

I think the first option makes more sense from an efficiency perspective since there's no need to allocate memory for a RestClient on every single `Send`

2023-01-04 19:12 UTC, natehitze commented on Dwolla.Client/DwollaClient.cs
> +                    SslOptions = new SslClientAuthenticationOptions { EnabledSslProtocols = SslProtocols.Tls }
This doesn't look like it forces 1.2 like the old code did

2023-01-05 14:16 UTC, IsaiahDahlberg commented on Dwolla.Client/Dwolla.Client.csproj
> +    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
This is needed to have a Static HttpClientFactory

2023-01-05 18:20 UTC, natehitze commented
I pushed commits to fix the HttpClient to be what I think MS guidance says to do. Kind of a bummer that their advice for framework is to use their DI system that was introduced in core... which means most framework projects aren't using it.

`DateOnlyConverter` needs test coverage and then run the Example app (in docker if needed, they have a dockerfile provided) just to check that everything still works as expected. I think then if that all looks good then you can close this PR and open a PR in the Dwolla repo.

2023-01-09 19:53 UTC, natehitze approved these changes

2023-03-30 13:22 UTC, closed without merging